# Generated by Django 4.2.5 on 2024-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
