# Generated by Django 4.2.5 on 2024-04-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_alter_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
    ]
